### ISSUE TITLE
Controlling the SPA (target temperature, heat, filter, etc)

### ISSUE THREAD

**Issue by davyrolink** [claudiospizzi/node-red-contrib-intexspa#1]
Hi Claudio,

Thanks for writing this already great module. I'm curious if you plan to make it possible to control the SPA as well? It would be very nice to be able to control e.g. the temperature and filtering.

Regards, Davy

**Comment by claudiospizzi** [comment]
Hi @davyrolink 

It took me a while to figure out the API for the SPA control. I've released an update to version 2.0.0 which includes a node to perform an action, e.g. turn on/off the heating. I wonder if it's working with your SPA.

I've also fixed a bug not refreshing the cloud status ans still showing old values.

Please be aware, there is a breaking change:
The device name is now part of the configuration node.

Regards,
Claudio

**Comment by davyrolink** [comment]
Wow I am very excited to see this, I will try it out immediately this weekend. Thank you so much!

**Comment by davyrolink** [comment]
I have been able to test it extensively and it works great, thanks again

**Comment by claudiospizzi** [comment]
Hey @davyrolink 

Thanks for the feedback and your generous support!

Regards,
Claudio
